# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui',
# licensing of 'MainWindow.ui' applies.
#
# Created: Sun Mar 24 01:43:20 2019
#      by: pyside2-uic  running on PySide2 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1188, 349)
        font = QtGui.QFont()
        font.setPointSize(12)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.InputIp = QtWidgets.QLineEdit(self.centralwidget)
        self.InputIp.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.InputIp.setFont(font)
        self.InputIp.setText("")
        self.InputIp.setObjectName("InputIp")
        self.gridLayout.addWidget(self.InputIp, 1, 0, 1, 1)
        self.ButtonIp = QtWidgets.QPushButton(self.centralwidget)
        self.ButtonIp.setMaximumSize(QtCore.QSize(100, 50))
        self.ButtonIp.setObjectName("ButtonIp")
        self.gridLayout.addWidget(self.ButtonIp, 2, 0, 1, 1)
        self.ButtonRead = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ButtonRead.sizePolicy().hasHeightForWidth())
        self.ButtonRead.setSizePolicy(sizePolicy)
        self.ButtonRead.setMaximumSize(QtCore.QSize(100, 50))
        self.ButtonRead.setObjectName("ButtonRead")
        self.gridLayout.addWidget(self.ButtonRead, 7, 0, 1, 1)
        self.ButtonWrite = QtWidgets.QPushButton(self.centralwidget)
        self.ButtonWrite.setMaximumSize(QtCore.QSize(100, 50))
        self.ButtonWrite.setObjectName("ButtonWrite")
        self.gridLayout.addWidget(self.ButtonWrite, 7, 1, 1, 1)
        self.TextReadResult = QtWidgets.QTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TextReadResult.sizePolicy().hasHeightForWidth())
        self.TextReadResult.setSizePolicy(sizePolicy)
        self.TextReadResult.setMinimumSize(QtCore.QSize(0, 30))
        self.TextReadResult.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.TextReadResult.setObjectName("TextReadResult")
        self.gridLayout.addWidget(self.TextReadResult, 8, 0, 1, 1)
        self.InputWrite = QtWidgets.QLineEdit(self.centralwidget)
        self.InputWrite.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.InputWrite.setFont(font)
        self.InputWrite.setObjectName("InputWrite")
        self.gridLayout.addWidget(self.InputWrite, 4, 1, 1, 1)
        self.InputValue = QtWidgets.QLineEdit(self.centralwidget)
        self.InputValue.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.InputValue.setFont(font)
        self.InputValue.setObjectName("InputValue")
        self.gridLayout.addWidget(self.InputValue, 5, 1, 1, 1)
        self.InputRead = QtWidgets.QLineEdit(self.centralwidget)
        self.InputRead.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.InputRead.setFont(font)
        self.InputRead.setObjectName("InputRead")
        self.gridLayout.addWidget(self.InputRead, 4, 0, 1, 1)
        self.TextWriteResult = QtWidgets.QTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TextWriteResult.sizePolicy().hasHeightForWidth())
        self.TextWriteResult.setSizePolicy(sizePolicy)
        self.TextWriteResult.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.TextWriteResult.setFont(font)
        self.TextWriteResult.setObjectName("TextWriteResult")
        self.gridLayout.addWidget(self.TextWriteResult, 8, 1, 1, 1)
        self.TextStatus = QtWidgets.QTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TextStatus.sizePolicy().hasHeightForWidth())
        self.TextStatus.setSizePolicy(sizePolicy)
        self.TextStatus.setMinimumSize(QtCore.QSize(0, 30))
        self.TextStatus.setMaximumSize(QtCore.QSize(16777215, 30))
        self.TextStatus.setObjectName("TextStatus")
        self.gridLayout.addWidget(self.TextStatus, 3, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.InputIp, self.ButtonIp)
        MainWindow.setTabOrder(self.ButtonIp, self.InputRead)
        MainWindow.setTabOrder(self.InputRead, self.ButtonRead)
        MainWindow.setTabOrder(self.ButtonRead, self.InputValue)
        MainWindow.setTabOrder(self.InputValue, self.ButtonWrite)
        MainWindow.setTabOrder(self.ButtonWrite, self.InputWrite)
        MainWindow.setTabOrder(self.InputWrite, self.TextReadResult)
        MainWindow.setTabOrder(self.TextReadResult, self.TextWriteResult)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "TimeClock", None, -1))
        self.InputIp.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "Ip Address", None, -1))
        self.ButtonIp.setText(QtWidgets.QApplication.translate("MainWindow", "Connect", None, -1))
        self.ButtonRead.setText(QtWidgets.QApplication.translate("MainWindow", "Read", None, -1))
        self.ButtonWrite.setText(QtWidgets.QApplication.translate("MainWindow", "Write", None, -1))
        self.TextReadResult.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "Read result", None, -1))
        self.InputWrite.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "Variable", None, -1))
        self.InputValue.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "New Value", None, -1))
        self.InputRead.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "Variable", None, -1))
        self.TextWriteResult.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "Write result", None, -1))
        self.TextStatus.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "Status", None, -1))

