# Generated by Django 2.2.1 on 2019-05-26 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read_write_variable', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='variable',
            name='description',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
