# Generated by Django 2.2.1 on 2019-05-29 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('read_write_variable', '0002_auto_20190526_1238'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variable',
            options={'ordering': ('description',)},
        ),
    ]
